 // Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int N = Integer.parseInt(args[0]);
		int counter = 0;
		int countGreater = 0;
		int cuontSmaller = 0;
		double currentnum;

		while (counter < N) {
			currentnum = Math.random();
			if (currentnum > 0.5) { countGreater ++; }
				else				{ cuontSmaller ++; }
			counter ++;
		}
		
		System.out.println("> 0.5: " + countGreater + " times");
		System.out.println("<= 0.5: " + cuontSmaller + " times");

		double biggerNum = Math.max(countGreater, cuontSmaller);
		double smallerNum = Math.min(countGreater, cuontSmaller);
		if (smallerNum != 0) { System.out.println("Ratio: " + smallerNum / biggerNum);}
			
	}
}
